name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, curl, libxml

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Run tests
        run: composer test